### ISSUE TITLE
Verify the deploy steps on a windows

### ISSUE THREAD

**Issue by Steffeeeen1234** [Steffeeeen1234/MillControl#18]
VerfG the described steps in arduinoWebEditor.md on a windows machine.
Currently I don't have one. But if someone has, please verify the steps and note it in the Issue or create a nice PR for it

**Comment by madejackson** [comment]
Verified on Windows.

As well verified with Arduino IDE on Windows + Linux.

**Comment by Steffeeeen1234** [comment]
Hi, thanks. Than I can close this topic :)
